"""empty message

Revision ID: 02225c05cbee
Revises: 0462dbda427f
Create Date: 2019-08-03 00:20:02.510321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02225c05cbee'
down_revision = '0462dbda427f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assigned_measure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('stations', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stations'], ['station.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('unit')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assigned_measure')
    # ### end Alembic commands ###
