"""empty message

Revision ID: 1fff1a9ed0f9
Revises: a8dd127c23a8
Create Date: 2019-08-03 19:31:32.776320

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1fff1a9ed0f9'
down_revision = 'a8dd127c23a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignedmeasure', sa.Column('station_id', sa.Integer(), nullable=False))
    op.drop_constraint('assignedmeasure_ibfk_2', 'assignedmeasure', type_='foreignkey')
    op.create_foreign_key(None, 'assignedmeasure', 'station', ['station_id'], ['id'])
    op.drop_column('assignedmeasure', 'station')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignedmeasure', sa.Column('station', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'assignedmeasure', type_='foreignkey')
    op.create_foreign_key('assignedmeasure_ibfk_2', 'assignedmeasure', 'station', ['station'], ['id'])
    op.drop_column('assignedmeasure', 'station_id')
    # ### end Alembic commands ###
