"""empty message

Revision ID: 2ba40023c61f
Revises: d3ba4a763fc3
Create Date: 2019-08-03 00:59:22.931189

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ba40023c61f'
down_revision = 'd3ba4a763fc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('as_measure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('measure', sa.Integer(), nullable=False),
    sa.Column('station', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['measure'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['station'], ['station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('assigned_measure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assigned_measure',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('measure', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('station', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['measure'], ['measure.id'], name='assigned_measure_ibfk_1'),
    sa.ForeignKeyConstraint(['station'], ['station.id'], name='assigned_measure_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('as_measure')
    # ### end Alembic commands ###
