"""empty message

Revision ID: 37a5efc8d839
Revises: a82a8f2dcd58
Create Date: 2019-08-03 14:15:36.582403

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '37a5efc8d839'
down_revision = 'a82a8f2dcd58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station', sa.Column('responsible', sa.String(length=80), nullable=False))
    op.drop_column('station', 'responsibleUser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station', sa.Column('responsibleUser', mysql.VARCHAR(length=80), nullable=False))
    op.drop_column('station', 'responsible')
    # ### end Alembic commands ###
