"""empty message

Revision ID: 3aed3c1aad60
Revises: bee2b9661098
Create Date: 2019-08-03 19:21:29.456560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aed3c1aad60'
down_revision = 'bee2b9661098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station', sa.Column('person_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'station', 'person', ['person_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'station', type_='foreignkey')
    op.drop_column('station', 'person_id')
    # ### end Alembic commands ###
