"""empty message

Revision ID: 3d6ba6dd3f74
Revises: c94a7fcf076b
Create Date: 2019-08-02 23:42:36.145195

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d6ba6dd3f74'
down_revision = 'c94a7fcf076b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('organization', sa.Integer(), nullable=False))
    op.drop_constraint('person_ibfk_1', 'person', type_='foreignkey')
    op.create_foreign_key(None, 'person', 'organization', ['organization'], ['id'])
    op.drop_column('person', 'organization_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('organization_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'person', type_='foreignkey')
    op.create_foreign_key('person_ibfk_1', 'person', 'organization', ['organization_id'], ['id'])
    op.drop_column('person', 'organization')
    # ### end Alembic commands ###
