"""empty message

Revision ID: 443899a12073
Revises: a36a7210d875
Create Date: 2019-08-03 19:13:09.218555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443899a12073'
down_revision = 'a36a7210d875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'person', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='foreignkey')
    op.drop_column('person', 'organization_id')
    # ### end Alembic commands ###
