"""empty message

Revision ID: 507780e524d9
Revises: 78cd6fe2e8d4
Create Date: 2019-08-15 02:38:36.543972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507780e524d9'
down_revision = '78cd6fe2e8d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('data', sa.String(length=15), nullable=False))
    op.create_unique_constraint(None, 'data', ['data'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data', type_='unique')
    op.drop_column('data', 'data')
    # ### end Alembic commands ###
