"""empty message

Revision ID: 5340b84aef6f
Revises: 65b96537aeb1
Create Date: 2019-08-03 00:44:44.899708

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5340b84aef6f'
down_revision = '65b96537aeb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assigned_measure', sa.Column('measure', sa.Integer(), nullable=False))
    op.add_column('assigned_measure', sa.Column('station', sa.Integer(), nullable=False))
    op.drop_constraint('assigned_measure_ibfk_1', 'assigned_measure', type_='foreignkey')
    op.drop_constraint('assigned_measure_ibfk_2', 'assigned_measure', type_='foreignkey')
    op.create_foreign_key(None, 'assigned_measure', 'measure', ['measure'], ['id'])
    op.create_foreign_key(None, 'assigned_measure', 'station', ['station'], ['id'])
    op.drop_column('assigned_measure', 'measures')
    op.drop_column('assigned_measure', 'stations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assigned_measure', sa.Column('stations', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('assigned_measure', sa.Column('measures', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'assigned_measure', type_='foreignkey')
    op.drop_constraint(None, 'assigned_measure', type_='foreignkey')
    op.create_foreign_key('assigned_measure_ibfk_2', 'assigned_measure', 'measure', ['measures'], ['id'])
    op.create_foreign_key('assigned_measure_ibfk_1', 'assigned_measure', 'station', ['stations'], ['id'])
    op.drop_column('assigned_measure', 'station')
    op.drop_column('assigned_measure', 'measure')
    # ### end Alembic commands ###
