"""empty message

Revision ID: 65b96537aeb1
Revises: ef79faf36b58
Create Date: 2019-08-03 00:37:04.474675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65b96537aeb1'
down_revision = 'ef79faf36b58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('description', table_name='station')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('description', 'station', ['description'], unique=True)
    # ### end Alembic commands ###
