"""empty message

Revision ID: 68a146c6d10b
Revises: 981a7628e672
Create Date: 2019-08-09 01:25:02.148674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68a146c6d10b'
down_revision = '981a7628e672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measure', sa.Column('symbol', sa.String(length=10), nullable=False))
    op.create_unique_constraint(None, 'measure', ['symbol'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'measure', type_='unique')
    op.drop_column('measure', 'symbol')
    # ### end Alembic commands ###
