"""empty message

Revision ID: 75166cc8ebbe
Revises: 68a146c6d10b
Create Date: 2019-08-15 02:37:20.525777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75166cc8ebbe'
down_revision = '68a146c6d10b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('timestamp', table_name='data')
    op.drop_column('data', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('timestamp', mysql.VARCHAR(length=80), nullable=False))
    op.create_index('timestamp', 'data', ['timestamp'], unique=True)
    # ### end Alembic commands ###
