"""empty message

Revision ID: 78cd6fe2e8d4
Revises: 75166cc8ebbe
Create Date: 2019-08-15 02:38:07.272546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '78cd6fe2e8d4'
down_revision = '75166cc8ebbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('value', table_name='data')
    op.drop_column('data', 'value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('value', mysql.VARCHAR(length=80), nullable=False))
    op.create_index('value', 'data', ['value'], unique=True)
    # ### end Alembic commands ###
