"""empty message

Revision ID: 81b1cbdcc58b
Revises: 3aed3c1aad60
Create Date: 2019-08-03 19:21:57.562478

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '81b1cbdcc58b'
down_revision = '3aed3c1aad60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('station_ibfk_1', 'station', type_='foreignkey')
    op.drop_column('station', 'organization')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station', sa.Column('organization', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('station_ibfk_1', 'station', 'organization', ['organization'], ['id'])
    # ### end Alembic commands ###
