"""empty message

Revision ID: 82c49d3acd33
Revises: fbd8eb0607c0
Create Date: 2019-08-03 17:07:17.581180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82c49d3acd33'
down_revision = 'fbd8eb0607c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('station', 'responsibleuser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station', sa.Column('responsibleuser', mysql.VARCHAR(length=80), nullable=False))
    # ### end Alembic commands ###
