"""empty message

Revision ID: 85c214bda71e
Revises: 02225c05cbee
Create Date: 2019-08-03 00:21:10.394682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '85c214bda71e'
down_revision = '02225c05cbee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='assigned_measure')
    op.drop_index('unit', table_name='assigned_measure')
    op.drop_column('assigned_measure', 'name')
    op.drop_column('assigned_measure', 'unit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assigned_measure', sa.Column('unit', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('assigned_measure', sa.Column('name', mysql.VARCHAR(length=80), nullable=False))
    op.create_index('unit', 'assigned_measure', ['unit'], unique=True)
    op.create_index('name', 'assigned_measure', ['name'], unique=True)
    # ### end Alembic commands ###
