"""empty message

Revision ID: 981a7628e672
Revises: f503c2b7f6f8
Create Date: 2019-08-09 01:24:22.533146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981a7628e672'
down_revision = 'f503c2b7f6f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'measure', ['unit'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'measure', type_='unique')
    # ### end Alembic commands ###
