"""empty message

Revision ID: a04ca5f4bb30
Revises: 37a5efc8d839
Create Date: 2019-08-03 14:16:05.371531

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a04ca5f4bb30'
down_revision = '37a5efc8d839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station', sa.Column('responsibleuser', sa.String(length=80), nullable=False))
    op.drop_column('station', 'responsible')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station', sa.Column('responsible', mysql.VARCHAR(length=80), nullable=False))
    op.drop_column('station', 'responsibleuser')
    # ### end Alembic commands ###
