"""empty message

Revision ID: a36a7210d875
Revises: e9f50dad39c4
Create Date: 2019-08-03 19:11:28.831519

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a36a7210d875'
down_revision = 'e9f50dad39c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('person_ibfk_1', 'person', type_='foreignkey')
    op.drop_column('person', 'organization')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('organization', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('person_ibfk_1', 'person', 'organization', ['organization'], ['id'])
    # ### end Alembic commands ###
