"""empty message

Revision ID: a82a8f2dcd58
Revises: 2ba40023c61f
Create Date: 2019-08-03 01:01:06.624218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a82a8f2dcd58'
down_revision = '2ba40023c61f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignedmeasure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('measure', sa.Integer(), nullable=False),
    sa.Column('station', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['measure'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['station'], ['station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('as_measure')
    op.add_column('data', sa.Column('assignedmeasure', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'data', 'assignedmeasure', ['assignedmeasure'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data', type_='foreignkey')
    op.drop_column('data', 'assignedmeasure')
    op.create_table('as_measure',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('measure', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('station', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['measure'], ['measure.id'], name='as_measure_ibfk_1'),
    sa.ForeignKeyConstraint(['station'], ['station.id'], name='as_measure_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('assignedmeasure')
    # ### end Alembic commands ###
