"""empty message

Revision ID: a8dd127c23a8
Revises: cc00505f378a
Create Date: 2019-08-03 19:30:41.122073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8dd127c23a8'
down_revision = 'cc00505f378a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignedmeasure', sa.Column('measure_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'assignedmeasure', 'measure', ['measure_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assignedmeasure', type_='foreignkey')
    op.drop_column('assignedmeasure', 'measure_id')
    # ### end Alembic commands ###
