"""empty message

Revision ID: ad92c5e2e9b3
Revises: 85c214bda71e
Create Date: 2019-08-03 00:29:15.508355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad92c5e2e9b3'
down_revision = '85c214bda71e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assigned_measure', sa.Column('name', sa.String(length=80), nullable=False))
    op.add_column('assigned_measure', sa.Column('unit', sa.String(length=10), nullable=False))
    op.create_unique_constraint(None, 'assigned_measure', ['unit'])
    op.create_unique_constraint(None, 'assigned_measure', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assigned_measure', type_='unique')
    op.drop_constraint(None, 'assigned_measure', type_='unique')
    op.drop_column('assigned_measure', 'unit')
    op.drop_column('assigned_measure', 'name')
    # ### end Alembic commands ###
