"""empty message

Revision ID: bee2b9661098
Revises: 443899a12073
Create Date: 2019-08-03 19:20:13.712078

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bee2b9661098'
down_revision = '443899a12073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('station_ibfk_2', 'station', type_='foreignkey')
    op.drop_column('station', 'responsible')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station', sa.Column('responsible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('station_ibfk_2', 'station', 'person', ['responsible'], ['id'])
    # ### end Alembic commands ###
