"""empty message

Revision ID: cb19f28f6ea2
Revises: 1fff1a9ed0f9
Create Date: 2019-08-07 16:44:46.025505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb19f28f6ea2'
down_revision = '1fff1a9ed0f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station', sa.Column('streetaddress', sa.String(length=80), nullable=False))
    op.create_unique_constraint(None, 'station', ['streetaddress'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'station', type_='unique')
    op.drop_column('station', 'streetaddress')
    # ### end Alembic commands ###
