"""empty message

Revision ID: cc00505f378a
Revises: df3d0443469e
Create Date: 2019-08-03 19:30:08.443691

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc00505f378a'
down_revision = 'df3d0443469e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('assignedmeasure_ibfk_1', 'assignedmeasure', type_='foreignkey')
    op.drop_column('assignedmeasure', 'measure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignedmeasure', sa.Column('measure', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('assignedmeasure_ibfk_1', 'assignedmeasure', 'measure', ['measure'], ['id'])
    # ### end Alembic commands ###
