"""empty message

Revision ID: df3d0443469e
Revises: 81b1cbdcc58b
Create Date: 2019-08-03 19:22:26.489516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df3d0443469e'
down_revision = '81b1cbdcc58b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'station', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'station', type_='foreignkey')
    op.drop_column('station', 'organization_id')
    # ### end Alembic commands ###
