"""empty message

Revision ID: e9f50dad39c4
Revises: 82c49d3acd33
Create Date: 2019-08-03 17:08:57.637805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9f50dad39c4'
down_revision = '82c49d3acd33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station', sa.Column('responsible', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'station', 'person', ['responsible'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'station', type_='foreignkey')
    op.drop_column('station', 'responsible')
    # ### end Alembic commands ###
