"""empty message

Revision ID: ef79faf36b58
Revises: 5c83e35d02eb
Create Date: 2019-08-03 00:32:56.434477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef79faf36b58'
down_revision = '5c83e35d02eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assigned_measure', sa.Column('measures', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'assigned_measure', 'measure', ['measures'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assigned_measure', type_='foreignkey')
    op.drop_column('assigned_measure', 'measures')
    # ### end Alembic commands ###
