"""empty message

Revision ID: f503c2b7f6f8
Revises: 2ddbba87c664
Create Date: 2019-08-07 18:05:38.705232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f503c2b7f6f8'
down_revision = '2ddbba87c664'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='measure')
    op.drop_index('unit', table_name='measure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('unit', 'measure', ['unit'], unique=True)
    op.create_index('name', 'measure', ['name'], unique=True)
    # ### end Alembic commands ###
